### ISSUE TITLE
I cannot run the daemon

### ISSUE THREAD

**Issue by bruceleeon** [Saronite/saronite#4]
Creating the logger system
2018-Jun-10 15:58:53.469296 Initializing cryptonote protocol...
2018-Jun-10 15:58:53.469329 Cryptonote protocol initialized OK
2018-Jun-10 15:58:53.469535 Initializing p2p server...
2018-Jun-10 15:58:53.670694 Set limit-up to 4096 kB/s
2018-Jun-10 15:58:53.670793 Set limit-down to 8192 kB/s
2018-Jun-10 15:58:53.670841 Set limit-up to 4096 kB/s
2018-Jun-10 15:58:53.670896 Set limit-down to 8192 kB/s
2018-Jun-10 15:58:53.671001 Binding on 0.0.0.0:55444
2018-Jun-10 15:58:53.671105 Net service bound to 0.0.0.0:55444
2018-Jun-10 15:58:53.671128 Attempting to add IGD port mapping.
2018-Jun-10 15:58:57.675659 No IGD was found.
2018-Jun-10 15:58:57.675718 P2p server initialized OK
2018-Jun-10 15:58:57.675854 Initializing core rpc server...
2018-Jun-10 15:58:57.675937 Binding on 0.0.0.0:55445
2018-Jun-10 15:58:57.676049 Core rpc server initialized OK on port: 55445
2018-Jun-10 15:58:57.676091 Initializing core...
Aborted

**Comment by bruceleeon** [comment]
Creating the logger system
2018-Jun-10 16:02:44.215423 Initializing cryptonote protocol...
2018-Jun-10 16:02:44.215481 Cryptonote protocol initialized OK
2018-Jun-10 16:02:44.215701 Initializing p2p server...
2018-Jun-10 16:02:44.274863 Set limit-up to 4096 kB/s
2018-Jun-10 16:02:44.275013 Set limit-down to 8192 kB/s
2018-Jun-10 16:02:44.275083 Set limit-up to 4096 kB/s
2018-Jun-10 16:02:44.275177 Set limit-down to 8192 kB/s
2018-Jun-10 16:02:44.275327 Binding on 0.0.0.0:55444
2018-Jun-10 16:02:44.275472 Net service bound to 0.0.0.0:55444
2018-Jun-10 16:02:44.275512 Attempting to add IGD port mapping.
2018-Jun-10 16:02:48.279474 No IGD was found.
2018-Jun-10 16:02:48.279563 P2p server initialized OK
2018-Jun-10 16:02:48.279714 Initializing core rpc server...
2018-Jun-10 16:02:48.279849 Binding on 127.0.0.1:55445
2018-Jun-10 16:02:48.279956 Core rpc server initialized OK on port: 55445
2018-Jun-10 16:02:48.280001 Initializing core...
2018-Jun-10 16:02:48.280220 Loading blockchain from folder /home/saronitedaemon/.saronite/lmdb ...
2018-Jun-10 16:02:48.280290 option: fast
2018-Jun-10 16:02:48.280318 option: async
2018-Jun-10 16:02:48.280337 option: 1000
2018-Jun-10 16:02:48.280710 Error attempting to retrieve a hard fork version at height 0 from the db: MDB_NOTFOUND: No matching key/data pair found
Aborted

**Comment by bruceleeon** [comment]
No, the daemon is "Aborted" constantly

**Comment by reeyon** [comment]
`2018-Aug-21 11:43:35.031427 Core rpc server initialized OK on port: 55445
2018-Aug-21 11:43:35.031521 Initializing core...
2018-Aug-21 11:43:35.031979 Locking /root/.saronite/.daemon_lock
2018-Aug-21 11:43:35.032106 BlockchainLMDB::BlockchainLMDB
2018-Aug-21 11:43:35.032187 BlockchainLMDB::get_db_name
2018-Aug-21 11:43:35.032269 Loading blockchain from folder /root/.saronite/lmdb ...
2018-Aug-21 11:43:35.032373 option: fast
2018-Aug-21 11:43:35.032456 option: async
2018-Aug-21 11:43:35.032534 option: 1000
2018-Aug-21 11:43:35.032643 BlockchainLMDB::open
2018-Aug-21 11:43:35.033020 BlockchainLMDB::need_resize
2018-Aug-21 11:43:35.033116 DB map size:     1073741824
2018-Aug-21 11:43:35.033201 Space used:      36864
2018-Aug-21 11:43:35.033282 Space remaining: 1073704960
2018-Aug-21 11:43:35.033365 Size threshold:  0
2018-Aug-21 11:43:35.033500 Percent used: 0.0000  Percent threshold: 0.8000
2018-Aug-21 11:43:35.033718 Setting m_height to: 0
2018-Aug-21 11:43:35.033926 mdb_txn_safe: destructor
2018-Aug-21 11:43:35.034030 Blockchain::init
2018-Aug-21 11:43:35.034119 BlockchainLMDB::height
2018-Aug-21 11:43:35.034197 BlockchainLMDB::check_open
2018-Aug-21 11:43:35.034332 BlockchainLMDB::block_rtxn_start
2018-Aug-21 11:43:35.034414 mdb_txn_safe: destructor
2018-Aug-21 11:43:35.034499 BlockchainLMDB::get_hard_fork_version
2018-Aug-21 11:43:35.034612 BlockchainLMDB::check_open
2018-Aug-21 11:43:35.034702 BlockchainLMDB::block_rtxn_start
2018-Aug-21 11:43:35.034802 Error attempting to retrieve a hard fork version at height 0 from the db: MDB_NOTFOUND: No matching key/data pair found
2018-Aug-21 11:43:35.047262 mdb_txn_safe: destructor
Aborted (core dumped)
`

**Comment by TheArchangelDev** [comment]
You need to recompile the code using: make release-static
