### ISSUE TITLE
New daemon no longer functions

### ISSUE THREAD

**Issue by ns1000** [Saronite/saronite#5]
No longer syncs:

2018-Jun-12 11:03:57.848333 [P2P4]ERROR /root/temp/daa/saronite/src/cryptonote_core/checkpoints.cpp:108 CHECKPOINT FAILED FOR HEIGHT 27295. EXPECTED HASH: <37ad1021188c63ab61bab4b729466a3c47824c269587169ad2c7e6160bf619c6>, FETCHED HASH: <d4e2303cf11dea916bf7ffe9ff831b4c8978f107ca405a97ffbff27fe76c3a8e>
2018-Jun-12 11:03:57.848842 [P2P4]ERROR /root/temp/daa/saronite/src/cryptonote_core/blockchain.cpp:3159 CHECKPOINT VALIDATION FAILED

**Comment by Saronite** [comment]
That is because you are trying to sync only with daemons that are on a bad chain.
